### ISSUE TITLE
Missing p315 data in DATASET_MatchaTTS/train directory, but referenced in train.txt

### ISSUE THREAD

**Issue by WWWWWLI** [isjwdu/DFADD#1]
It seems that the data for p315 is missing in the DATASET_MatchaTTS/train/ directory. However, p315 is still referenced in the train.txt file. Could you please check if the p315 data has been misplaced or omitted, and update the dataset accordingly?

**Comment by isjwdu** [comment]
Hi, thank you for pointing out the mistake.
I have removed the list of spoof data for speaker p315 from train.txt. You now can download DATASET_MatchaTTS in HuggingFace again.
As for why spoofed data for p315 is not generated, it's because Matcha-TTS requires a speaker mapping list to perform VCTK voice inference, but the official repo does not provide this list. I found a similar file list (https://github.com/jaywalnut310/vits/blob/main/filelists/vctk_audio_sid_text_train_filelist.txt) to use for speaker mapping. In this file list, p315 is not included.
